server:
  port: 5100

spring:
  profiles:
    active: local

---
spring:
  profiles: local


---
spring:
  profiles: docker
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:mysql://mysql:3306
    username: root
    password: 123456
    initialization-mode: always
  redis:
    host: redis
  rabbitmq:
    host: rabbitmq